# Generated by Django 3.0 on 2019-12-09 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1, verbose_name='Номер этажа')),
                ('name', models.CharField(max_length=100, verbose_name='Описание')),
                ('has_toilet', models.BooleanField(default=False, verbose_name='Есть туалет')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Номер')),
                ('description', models.CharField(max_length=100, verbose_name='Описание')),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='floor', to='toy.Floor')),
            ],
        ),
    ]
